### ISSUE TITLE
SAMLANG example code clips other elements when scrolling down

### ISSUE THREAD

**Issue by ptwu** [SamChou19815/website#582] opened 2020-05-27 04:44 UTC
**Describe the bug**
In 1600x900 and 1920x1080 window sizes, scrolling down the homepage results in the example SAMLANG code clipping over the card information.

**To Reproduce**
👀 View the site in 1600x900 and up. Strange behavior also happens at small screen widths where the About card clips the example SAMLANG code on the LHS.

**Screenshots**
![Video of bug](https://user-images.githubusercontent.com/7517829/82978496-b7828200-9fb2-11ea-8459-6e719487f9c4.gif)

**Environment**
 - Browser: Chrome 81.0.4044.138
 - OS: Windows 10

**Notes**
The redesign looks really clean, great job :devsam:

**Comment by SamChou19815** [comment] 2020-05-27 05:27
Weird enough, I cannot reproduce this problem on mac, but I can reproduce it on my windows VM with firefox. 🤔

**Comment by SamChou19815** [comment] 2020-05-27 05:33
Should be fixed in #583. Windows really doesn't like flexbox 😢

**Closed by SamChou19815** 2020-05-27 05:33 UTC
Labels: good first issue
